spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/testeinfuse?useTimezone=true&serverTimezone=UTC'
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo

  flyway:
    enabled: true
    user: ${spring.datasource.username}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    table: flyway_schema_history